spring:
  application:
    name: restaurant

  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


security:
  jwt:
    secret: ${JWT_SECRET:0RGrUlA27pl/5EiSNW2eD22QjMuD2QV+QeBQIYlvX/o=}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}